api:
  version: 1.0.0

server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze94ns7xf3ho49rjko.mysql.rds.aliyuncs.com:3306/revolt_big_data?useSSL=false
    username: rbd_dev
    password: rbd_dev
  thymeleaf:
    cache: false

logging:
  path: log/

url:
  jd:
    priceBySkuId: https://p.3.cn/prices/mgets
    skuIdByKeyword: https://search.jd.com/Search?enc=utf-8&keyword=

