api:
  version: 1.0.0

server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze94ns7xf3ho49rjko.mysql.rds.aliyuncs.com:3306/revolt_big_data?useSSL=false
    username: rbd_dev
    password: rbd_dev
  thymeleaf:
    cache: false
  #日志着色
  output:
    ansi:
      enabled: ALWAYS

logging:
  path: log/

url:
  jd:
    #根据skuId查询价格
    priceBySkuId: https://p.3.cn/prices/mgets
    #商品详情url+skuId.html
    itemUrl: https://item.jd.com/
    #关键字查询url
    skuIdByKeyword: https://search.jd.com/Search?enc=utf-8&keyword=
